# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxCocoa-TableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxCocoa-TableView
  pod 'RxSwift', '6.0.0.rc-2'
  pod 'RxCocoa', '6.0.0.rc-2'
  pod 'RxRelay'
  pod 'SnapKit'

  target 'RxCocoa-TableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxCocoa-TableViewUITests' do
    # Pods for testing
  end

end
