# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rx_Swift_Study' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rx_Swift_Study
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'Rx_Swift_StudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Rx_Swift_StudyUITests' do
    # Pods for testing
  end

end
